security:
  basic:
    enabled: false

management:
  endpoint:
    web:
      exposure:
        include: *
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: false

quoteServiceURL: http://quote-service-dev.cfapps.io/quote